"""add address seller

Revision ID: 5849a676773d
Revises: 77df1fc746f7
Create Date: 2025-08-31 23:17:22.225816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '5849a676773d'
down_revision: Union[str, Sequence[str], None] = '77df1fc746f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
