"""add shipment status

Revision ID: 760ec9ed3c6f
Revises: dbe221bb106a
Create Date: 2025-09-08 15:52:25.205454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760ec9ed3c6f'
down_revision: Union[str, Sequence[str], None] = 'dbe221bb106a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE shipmentstatus ADD VALUE 'cancelled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
