"""add delivery partner and timestamp

Revision ID: 8c5fba447f81
Revises: 5849a676773d
Create Date: 2025-09-02 13:26:16.944238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = '8c5fba447f81'
down_revision: Union[str, Sequence[str], None] = '5849a676773d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
    sa.Column('name', AutoString(), nullable=False),
    sa.Column('email', AutoString(), nullable=False),
    sa.Column('password', AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seller', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('shipment', sa.Column('delivery_partner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('shipment_delivery_partner', 'shipment', 'delivery_partner', ['delivery_partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shipment_delivery_partner', 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'delivery_partner_id')
    op.drop_column('shipment', 'created_at')
    op.drop_column('seller', 'created_at')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
