"""add email verified user

Revision ID: da43646765bf
Revises: 1a9544aa64ac
Create Date: 2025-09-10 10:34:31.006528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da43646765bf'
down_revision: Union[str, Sequence[str], None] = '1a9544aa64ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
